import type { ExerciseTemplate } from '../types/workout.js';

export const exerciseLibrary: ExerciseTemplate[] = [
  {
    name: 'Push-ups',
    category: 'Strength',
    muscleGroups: ['chest', 'triceps', 'shoulders'],
    difficulty: 'Beginner',
    equipment: ['bodyweight'],
    instructions: 'Keep a straight body line, lower until elbows reach about 90 degrees, then press up.',
    videoUrl: 'https://youtu.be/bQvuy5f5j-8',
    thumbnailUrl: 'https://img.youtube.com/vi/bQvuy5f5j-8/maxresdefault.jpg',
    trackingType: 'reps',
  },
  {
    name: 'Goblet Squat',
    category: 'Strength',
    muscleGroups: ['quadriceps', 'glutes', 'core'],
    difficulty: 'Beginner',
    equipment: ['dumbbell', 'kettlebell'],
    instructions: 'Hold the weight close to your chest, sit hips down and back, then drive through heels.',
    videoUrl: '',
    thumbnailUrl: '',
    trackingType: 'reps',
  },
  {
    name: 'Dumbbell Bench Press',
    category: 'Strength',
    muscleGroups: ['chest', 'triceps', 'shoulders'],
    difficulty: 'Intermediate',
    equipment: ['dumbbell', 'bench'],
    instructions: 'Press dumbbells from chest level to locked arms while keeping shoulder blades stable.',
    videoUrl: '',
    thumbnailUrl: '',
    trackingType: 'reps',
  },
  {
    name: 'Lat Pulldown',
    category: 'Strength',
    muscleGroups: ['back', 'biceps'],
    difficulty: 'Beginner',
    equipment: ['machine'],
    instructions: 'Pull the bar to upper chest, keep ribs down, and control the return.',
    videoUrl: '',
    thumbnailUrl: '',
    trackingType: 'reps',
  },
  {
    name: 'Romanian Deadlift',
    category: 'Strength',
    muscleGroups: ['hamstrings', 'glutes', 'back'],
    difficulty: 'Intermediate',
    equipment: ['barbell', 'dumbbell'],
    instructions: 'Hinge at the hips, keep back neutral, lower until hamstrings stretch, then stand tall.',
    videoUrl: '',
    thumbnailUrl: '',
    trackingType: 'reps',
  },
  {
    name: 'Walking Lunges',
    category: 'Strength',
    muscleGroups: ['quadriceps', 'glutes', 'hamstrings'],
    difficulty: 'Intermediate',
    equipment: ['bodyweight', 'dumbbell'],
    instructions: 'Step forward, lower both knees with control, then drive into the next step.',
    videoUrl: '',
    thumbnailUrl: '',
    trackingType: 'reps',
  },
  {
    name: 'Plank Hold',
    category: 'Strength',
    muscleGroups: ['core', 'shoulders'],
    difficulty: 'Beginner',
    equipment: ['bodyweight'],
    instructions: 'Hold a straight line from head to heels while breathing steadily.',
    videoUrl: '',
    thumbnailUrl: '',
    trackingType: 'time',
  },
  {
    name: 'Cable Row',
    category: 'Strength',
    muscleGroups: ['back', 'biceps'],
    difficulty: 'Beginner',
    equipment: ['machine', 'cable'],
    instructions: 'Pull handle toward ribs, squeeze shoulder blades, and return with control.',
    videoUrl: '',
    thumbnailUrl: '',
    trackingType: 'reps',
  },
  {
    name: 'Shoulder Press',
    category: 'Strength',
    muscleGroups: ['shoulders', 'triceps'],
    difficulty: 'Intermediate',
    equipment: ['dumbbell', 'machine'],
    instructions: 'Press overhead without arching your lower back, then lower to shoulder height.',
    videoUrl: '',
    thumbnailUrl: '',
    trackingType: 'reps',
  },
  {
    name: 'Incline Treadmill Walk',
    category: 'Cardio',
    muscleGroups: ['cardio', 'glutes', 'calves'],
    difficulty: 'Beginner',
    equipment: ['treadmill'],
    instructions: 'Walk at a steady pace with tall posture and controlled breathing.',
    videoUrl: '',
    thumbnailUrl: '',
    trackingType: 'time',
  },
];
